### ISSUE TITLE
Rails 4.2 support

### ISSUE THREAD

**Issue by arunagw** [asanghi/serial_preference#5]
Seems like this gem will not work with rails 4.2 as there are some changes needs to be done.

What I understand and needs to be change inside `PreferenceDefinition`

```
ActiveRecord::ConnectionAdapters::Column.new(name.to_s,opts[:default],@type.to_s)
```

As after this https://github.com/rails/rails/commit/0b682e4b05c8f58c77c655650af6638c483ac903 we cannot just send `type` we have to send a type_cast object which can be like `ActiveRecord::Type::String.new`. But as it's a private to rails might not be a good idea to use this.

Looking for suggestions to fix this and get this gem working with rails 4.2

**Comment by asanghi** [comment]
I think we need to consider if we really need this gem in Rails 4.2 first. Is it even relevant?

**Comment by arunagw** [comment]
Closing as #6 is merged
